<?php

namespace Dev\PCultBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RepresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentationRepository extends EntityRepository
{
}
