representation:
    pattern:  /
    defaults: { _controller: "DevPCultBundle:Representation:index" }

representation_show:
    pattern:  /{id}/show
    defaults: { _controller: "DevPCultBundle:Representation:show" }

representation_new:
    pattern:  /new
    defaults: { _controller: "DevPCultBundle:Representation:new" }

representation_create:
    pattern:  /create
    defaults: { _controller: "DevPCultBundle:Representation:create" }
    requirements: { _method: post }

representation_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "DevPCultBundle:Representation:edit" }

representation_update:
    pattern:  /{id}/update
    defaults: { _controller: "DevPCultBundle:Representation:update" }
    requirements: { _method: post|put }

representation_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "DevPCultBundle:Representation:delete" }
    requirements: { _method: post|delete }
